# k8s/deployment-demo.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx
  labels:
    app: influx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influx
  template:
    metadata:
        labels:
          app: influx
    spec:
      containers:
      - name: server
        image: influxdb:1.8.10
        env:
        - name: INFLUXDB_HTTP_AUTH_ENABLED
          value: "false"
        - name: INFLUXDB_ADMIN_USER
          value: "influx_user"
        - name: INFLUXDB_ADMIN_PASSWORD
          value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: influx-service
spec:
  selector:
    app: influx
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086

